use readonly flag for command name variable

diff --git a/macos b/macos
--- a/macos
+++ b/macos
@@ -1,15 +1,15 @@
 #!/bin/bash
 set -euxo pipefail
 
-cmdname="$(basename "${BASH_SOURCE[0]}")"
+readonly CMDNAME="${BASH_SOURCE[0]##*/}"
 
 if ! command -v defaults >/dev/null; then
-  echo "$cmdname: defaults not found" >&2
+  echo "$CMDNAME: defaults not found" >&2
   exit
 fi
 
 if ! command -v osascript >/dev/null; then
-  echo "$cmdname: osascript not found" >&2
+  echo "$CMDNAME: osascript not found" >&2
   exit
 fi
 
diff --git a/script/ci b/script/ci
--- a/script/ci
+++ b/script/ci
@@ -1,12 +1,12 @@
 #!/bin/bash
 set -euxo pipefail
 
-cmdname="$(basename "${BASH_SOURCE[0]}")"
+readonly CMDNAME="${BASH_SOURCE[0]##*/}"
 
 cd "$(dirname "$0")/.."
 
 if ! command -v shellcheck >/dev/null; then
-  echo "$cmdname: shellcheck is required" >&2
+  echo "$CMDNAME: shellcheck is required" >&2
   exit 1
 fi
 
