use >&2 instead of >/dev/stderr

diff --git a/macos b/macos
--- a/macos
+++ b/macos
@@ -4,12 +4,12 @@ set -euxo pipefail
 cmdname="$(basename "${BASH_SOURCE[0]}")"
 
 if ! command -v defaults >/dev/null; then
-  echo "$cmdname: defaults not found" > /dev/stderr
+  echo "$cmdname: defaults not found" >&2
   exit
 fi
 
 if ! command -v osascript >/dev/null; then
-  echo "$cmdname: osascript not found" > /dev/stderr
+  echo "$cmdname: osascript not found" >&2
   exit
 fi
 
diff --git a/script/ci b/script/ci
--- a/script/ci
+++ b/script/ci
@@ -6,7 +6,7 @@ cmdname="$(basename "${BASH_SOURCE[0]}")"
 cd "$(dirname "$0")/.."
 
 if ! command -v shellcheck >/dev/null; then
-  echo "$cmdname: shellcheck is required" > /dev/stderr
+  echo "$cmdname: shellcheck is required" >&2
   exit 1
 fi
 
