check availability of shellcheck in script/ci

diff --git a/script/ci b/script/ci
--- a/script/ci
+++ b/script/ci
@@ -3,6 +3,11 @@ set -eux
 
 cd "$(dirname "$0")/.."
 
+if ! command -v shellcheck >/dev/null; then
+  echo "ci: shellcheck is required" > /dev/stderr
+  exit 1
+fi
+
 files=$(git ls-files -s | grep 755 | awk '{ print $4 }')
 
 for f in $files; do
